name: test
https://github.com/Curious-r/Actions-OpenWrt

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Build trigger
        if: needs.check.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: Lean LEDE source code update
