name: test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
